### ISSUE TITLE
FlexCloud: Setup spatial jobs

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#395]

**Comment by dnath** [comment]
Dependent on #397

**Comment by dnath** [comment]
Partially done in f3449192ea2862d7f1fcc6643df2705d2d420c64

Output is produced, dynamo_db & s3 are updated, has results, but html rendering is not successful, stuck on "Downloading data to browser..."

I don't know how the spatial HTML/JS render work --- need some help on this @bbbales2 @briandrawert 

Still need to fix #397 to get actual output rather than error logs, which is the case now

**Comment by bbbales2** [comment]
"Downloading data to browser..." issue fixed in https://github.com/StochSS/stochss/commit/31820a401dfdf398f75fbee2729a1af94f337610

**Comment by briandrawert** [comment]
Done, needs to be checked.

**Comment by briandrawert** [comment]
Fixed in #383
