### ISSUE TITLE
Flex timeout

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#491]
Can we make the timeout lower for checking Flex nodes?

When I have a flex system in a bad state it takes sooooo long for the pages to load. I think it's the timeout on line 82 of backend/agents/flex_agent.py.

**Comment by briandrawert** [comment]
The problem was actually that the page was trying to 'deregister' the inaccessible instances, rather that just report them as inaccessible.
Also fixed, the bug where the refresh button was just doing a 'document.reload()' instead of telling the backend to update the system.
The real problem was that deregister needs a timeout if the nodes are inaccessible.
All this fixed in fd0c1abf869d1d5c90c3b3a0fd3c3a5cd6246098

**Comment by bbbales2** [comment]
Confirmed fixed
