### ISSUE TITLE
Windows launcher

### ISSUE THREAD

**Issue by JohnAbel** [StochSS/stochss#590]
General thread for windows issues until we decide what to make independent issues

**Comment by JohnAbel** [comment]
After step:  "This will start/create a Virtual Machine called stochss1-7. StochSS will run in this machine" you need to connect your docker shell to the VM. It looks like the command to do this is:
> eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env stochss1-7)

**Comment by JohnAbel** [comment]
This
>docker run -i -t -p 8080:8080 -p 8000:8000 --name=stochsscontainer1_7 aviralcse/stochss-initial:1.7 "/bin/bash"
works. Up through this point the guide seems to work mostly.

**Comment by briandrawert** [comment]
Things to make more clear in the README:
- How to connect the VM running to Chrome:  "Navigate to http://..." line on the screenshot didn't work
- Note that you may have to enable virtualization in the BIOS (can we link to a howto somewhere). 
- Note that you need Win7 64 bit at least
- Since you can't copy/paste in the docker "terminal", shortening the commands would be easier (is this possible?)

**Comment by aviral26** [comment]
Issue - connect terminal to VM
Fix - 254fc2d1527e91ecc2a7b0c1cd74e16624e9c879

Issue - URL displayed incorrectly
Fix - I had encapsulated the arguments to the docker run command in diamond braces <> while writing the readme. This was incorrectly parsed by the markdown parser and not displayed. Fixed in 254fc2d1527e91ecc2a7b0c1cd74e16624e9c879

Issue - commands too long
Fix - The way to copy-paste commands into the docker toolbox terminal is simply "right click": that should paste into the terminal whatever is copied on the clipboard. To copy something from the docker-toolbox terminal, highlight it and then press enter/return - that would copy the highlighted text to your clipboard.

Issue - readme unclear
fix - c8302bf659203697dc110843eebc9f1f4a05032b

**Comment by JohnAbel** [comment]
after the eval "$(docker-machine env stochss1-7)" run > docker-machine ls to ensure you ave the right active machine

**Comment by JohnAbel** [comment]
After "docker start container..." for an already existing container, I think you need to docker attach stochsscontainer1_7 (for e.g.)

**Comment by aviral26** [comment]
Thanks for pointing that out. Fixed in ee7161edb8bfb5ddc1195b5f0a165608fff18d8b

**Comment by JohnAbel** [comment]
that is correct. I didn't need to create a token/key for myself. it's all good and running right now.

**Comment by aviral26** [comment]
If a token is not provided as an argument, we generate one.

**Comment by JohnAbel** [comment]
Thanks! All working now on my win7 64. Clear for release on my end.

**Comment by briandrawert** [comment]
Windows seems to work, closing this issue.
