### ISSUE TITLE
Issues with custom propensity

### ISSUE THREAD

**Issue by Princeofthebow** [StochSS/stochss#850]
Hello, I'm trying to run the following population model:

0 -> A,  r1 = (1+(A/40)^5)/(2+(A/40)^5) 'custom propensity function': 0 reactants, 1 product of A
A ->0, r2 =1/140*A 'custom propensity function': 1 reactants, 0 products of A (this can be done equivalently with rate paraments)
Initial condition = 50.

StochSS hangs and does not run a simulation preview.

**Comment by Princeofthebow** [comment]
Let me add that if I change r1 = F the simulation is correctly performed.

**Comment by briandrawert** [comment]
This issue is because "^" is not the symbol for raising to a power in python or C++.  If you change to "**" it will work with ODE simulation.

However, this is a fixed issue is GillesPy2 v1.4+  We will be updating StochSS.org with the latest version shortly.  Your current model should work as soon as we do this.

**Comment by briandrawert** [comment]
StochSS 2.0.1 was installed on app.stochss.org today.  It uses GillesPy2 v1.4.2, which fixes this issue.
